linters:
  enable-all: true
  disable:
  - exportloopref
  - wrapcheck
  - gosec
  - exhaustruct
  - gochecknoglobals
  - depguard
  - cyclop
  - err113
  - exhaustive
  - mnd
  - ireturn
  - tagliatelle
  - gomnd
  - inamedparam
  - execinquery
  - wsl
  - lll

output:
  formats: tab

run:
  timeout: 10s

linters-settings:
  nestif:
    min-complexity: 10
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/shaunschembri/elastictv)